intLinkedList: intLinkedList.o linkedList.o 
	gcc -o intLinkedList linkedList.o intLinkedList.o

intLinkedList.o: intLinkedList.c linkedList.h
	gcc -c intLinkedList.c linkedList.h 

linkedList.o: linkedList.c linkedList.h
	gcc -c linkedList.c linkedList.h
